### ISSUE TITLE
Converter Pipeline

### ISSUE THREAD

**Issue by andyl** [elixir-tools/tableau#101]
I fiddled with MDEx 0.2 this eve, and found some bugs in their Liquid converter.  

As a workaround, I replaced the MDEx 0.2 calls with [Solid](https://github.com/edgurgel/solid).  It worked perfectly.  I laughed at how simple it was.

Your current design, as I understand it, assumes that the template processing (Liquid) and the HTML Conversion (MDEx) will be bundled into a single converter tied to a filename extension.

I am posting to request a design that also allows for a "converter pipeline".  

In the pipeline, each converter module has a `convert` function that takes the same input arguments `{input_text, assigns}, opts`, and returns the same output `{output_text, assigns}`.  Re: the `converter: {md: <ARG>}` configuration - allow the ARG to also be a pipeline of converters eg `[Tableau.LiquidConverter, Tableau.MermaidConverter, Tableau.MDExConverter]`.  Let the default `converter` be defined in the application config `converter: {md: <ConverterModuleOrPipeline>}`, and make it possible to override in the frontmatter.

With this approach, it would be possible to mix and match in the field, without dependency on a super-converter.  Adding support for EEx, AsciiDocs, etc. would be IMO simple.  Each converter ought to be easy to test.

**Comment by mhanberg** [comment]
Was thinking, I think since this pipeline concept is particular to mdex currently and sort of relies on passing the ast through the pipeline, I think I'll make it so when you configure your converters, you can pass a tuple instead like `{MDExConverter, pipeline: [X, Y, Z]}` and the converter itself can do what it wants with those options.

**Comment by andyl** [comment]
> Can you elaborate?

Here is an example of my original "Liquid" converter that uses MDEx 0.2.

```elixir
defmodule Tableau.Liquid.MdexConverter do
  @moduledoc """
  This converter uses Mdex 0.2 to transform Liquid tags.
  """

  def convert({input_text, assigns}, _converter_options \\ []) do
    str_assigns = assigns |> stringify_keys()

    output_text =
      input_text
      |> MDEx.parse_document!()
      |> MDEx.traverse_and_update(fn
        # render each text as liquid template
        {node, attrs, children} ->
          children =
            Enum.reduce(children, [], fn
              child, acc when is_binary(child) ->
                with {:ok, template} <- Solid.parse(child),
                     {:ok, rendered} <- Solid.render(template, str_assigns) do
                  [to_string(rendered) | acc]
                else
                  _ -> [child | acc]
                end

              child, acc ->
                [child | acc]
            end)
            |> Enum.reverse()

          {node, attrs, children}
      end)

    {output_text, assigns}
  end

  defp stringify_keys(map) do
    Map.new(map, fn {k, v} -> {Atom.to_string(k), v} end)
  end
end
```

This converter suffers from bugs in the MDEx 0.2 code.  (eg statements like `{%
assign variable = "value" %}` are ignored)

To fix this problem, I rewrote the converter to use [Solid](https://github.com/edgurgel/solid) template engine.

```elixir
defmodule Tableau.Liquid.SolidConverter do
  @moduledoc """
  This converter uses the `Solid` template engine to transform Liquid tags.
  """

  def convert({input_text, assigns}, _converter_options \\ []) do
    str_assigns = assigns |> stringify_keys()

    {:ok, template} = Solid.parse(input_text)
    output_text = Solid.render!(template, str_assigns) |> to_string

    {output_text, assigns}
  end

  defp stringify_keys(map) do
    Map.new(map, fn {k, v} -> {Atom.to_string(k), v} end)
  end
end
```

Here is how the converters would be used in the current architecture:

```elixir
defmodule Tableau.PageExtension.Pages.HTMLConverter do
  @moduledoc false
  def convert(_filepath, body, attrs, _opts) do

    {:ok, config} = Tableau.Config.new(Map.new(Application.get_env(:tableau, :config, %{})))

    {body, attrs}
    |> Tableau.Liquid.SolidConverter.convert()
    |> elem(0)
    |> MDEx.to_html!(config.markdown[:mdex])
  end
end
```

**Comment by mhanberg** [comment]
I see, I think your solution would suffer from rendering liquid expressions inside code blocks, when the author might want to render them as is.

**Comment by andyl** [comment]
> I think your solution would suffer from rendering liquid expressions inside code blocks, when the author might want to render them as is.

Right.  Perhaps someone would write a converter option for that.

[{Tableau.Liquid.SolidConverter, [ignore: "code_blocks"]}, Tableau.MdexConverter]

**Comment by mhanberg** [comment]
> Regarding the MDEx liquid example not maintaining variable assignments, does the elixir-lang.org jekyll site do that in markdown files, or just something you tried and saw it didn't work?

I think `solid` could potentially be patched to allow the `Solid.render` function to return the updated context along with the markup, so you could reduce over templates and maintain any variables that are created.

**Comment by andyl** [comment]
> the pipeline concept is particular to a converter, in the case of mdex, you can pipe the ast through some transformers and then turn it into HTML

In my conception, each converter takes the same inputs, `{input_string, assigns}, converter_options` and produces the same output `{output_string, assigns}`.

Sort of like how `plug` works in phoenix.

In this world, there is no "assigning a pipeline to a converter".

You may have this config: 

```elixir 
config :tableau 
  converters: [ 
    md: Tableau.MDExConverter, 
    asciidoc: [MySite.LiquidConverter, Tableau.AsciidocConverter]
  ]
```

Or you may give options to a converter:

```elixir 
config :tableau 
  converters: [ 
    md: Tableau.MDExConverter, 
    asciidoc: [{MySite.LiquidConverter, [ignore: "code-blocks"]}, Tableau.AsciidocConverter]
  ]
```

The goal would be to make converters composable in userland, yes. 

To pass from converter to converter, IMO strings are a better abstraction than AST.  Within a converter, yes use AST if necessary.

> elixir-lang.org jekyll and liquid variable assignments

Yes, the elixir-lang.org site does make common use of variable assignments and conditionals, both of which fail in my implementation of the MDEx 0.2 Liquid handler.

**Comment by andyl** [comment]
> To me this is a leaky abstraction.

It would be possible for anyone to compose higher-level abstractions:

```elixir

defmodule My.DoItAllConverter do 
  def convert({input_text, assigns}, _converter_options \\ []) do 
    {input_text, assigns} 
    |> Tableau.LiquidConverter.convert()
    |> My.UpcaseHeadlinesConverter.convert([only: "H1"])
    |> Tableau.MDExConverter.convert()
  end

end
```

**Comment by andyl** [comment]
> you could reduce over <converters> and maintain any variables that are created

Yes!  Any converter in the pipeline could modify `output_text` and/or `assigns`

**Comment by mhanberg** [comment]
> > you could reduce over "converters" and maintain any variables that are created
> 
> Yes! Any converter in the pipeline could modify `output_text` and/or `assigns`
> 
> ```elixir
> defmodule ConverterRunner do
>   def reduce(pipeline, input_text, assigns) when is_list(pipeline) do
>     Enum.reduce(pipeline, {input_text, assigns}, fn
>       {converter, opts}, acc ->
>         converter.convert(acc, opts)
>       converter, acc ->
>         converter.convert(acc)
>     end)
>   end
> 
>   def reduce(converter, input_text, assigns) do 
>     reduce([converter], input_text, assigns) 
>   end
> end
> ```

I think you are misquoting me.

I said you can "reduce over templates", meaning the liquid templates in the MDEx example, if the return value of `Solid.render` was changed to `{:ok, rendered, context}`, where the context is the updated version of the bindings you passed into it. The problem with the MDEx example is that it treats each piece of liquid in the document as its only isolated liquid template, but documents are already written that expect it to be consumed as a single liquid template.

---

Aside from that, I think that to fit the use case of migrating a jekyll blog, writing a single combo converter is enough, and we can potentially revisit the pipeline concept later.

So for the case of the elixir-lang blog, the following custom converter should suffice

```elixir
defmodule ElixirLang.MarkdownLiquidConverter do
  def convert(_filepath, _front_matter, body, assigns) do
    {:ok, config} = Tableau.Config.get()

    body
    |> Solid.parse!()
    |> Solid.render!(stringify_keys(assigns))
    |> MDEx.to_html!(config.markdown[:mdex])
  end
end

**Comment by mhanberg** [comment]
Also for posterity, in my personal blog this is the function i use to stringify keys

```elixir
  def stringify(%struct{}) when struct not in [Date, DateTime, NaiveDateTime] do
    Map.from_struct(struct) |> stringify()
  end

  def stringify(%_struct{} = data) do
    data
  end

  def stringify(map) when is_map(map) do
    Map.new(map, fn
      {k, v} when is_atom(k) -> {to_string(k), stringify(v)}
      other -> other
    end)
  end

  def stringify(list) when is_list(list) do
    Enum.map(list, &stringify/1)
  end

  def stringify(other), do: other
```
