### ISSUE TITLE
Liquid Tags: Looking Good

### ISSUE THREAD

**Issue by andyl** [elixir-tools/tableau#103]
THANK YOU FOR TODAY'S RELEASE!!!

Markdown text embedded with Liquid Tags
![image](https://github.com/user-attachments/assets/f95c731c-0aee-49d4-bd6b-1fbf80d34360)

Renders to HTML!!  Tags are evaluated!!
![image](https://github.com/user-attachments/assets/a5e16209-01b6-428c-bc4a-957eed6226ec)

Looking good!!!

**Comment by mhanberg** [comment]
Nice!
