### ISSUE TITLE
Feature request: post-conversion callbacks

### ISSUE THREAD

**Issue by halostatue** [elixir-tools/tableau#107]
#87 was presented as a step toward supporting other converters (#100 offers a different way to do this), this was *actually* used in @paradox460's blog to transform generated images to those handled by Netlify as a post-processing step: https://github.com/paradox460/pdx.su/blob/main/lib/html_converter.ex

While I’m not going to be using Netlify or Netlify images, being able to attach callbacks is likely to be very useful for some rendering pipelines. (I’m aware of this because I’m starting from `pdx.su` as a template for a likely relaunch of my blog and I’m trying to better understand the pipeline involved.)

**Comment by andyl** [comment]
With 0.18 you can spec your own converter module.  (https://github.com/elixir-tools/tableau/pull/100/files#diff-ef8e1ddb9c04d292d851b4831455ab636cc348488773db56b39c800692860549)

So far I have been able to process Liquid tags embedded in Markdown.

**Comment by halostatue** [comment]
> With 0.18 you can spec your own converter module. (https://github.com/elixir-tools/tableau/pull/100/files#diff-ef8e1ddb9c04d292d851b4831455ab636cc348488773db56b39c800692860549)
> 
> So far I have been able to process Liquid tags embedded in Markdown.

This isn't about preprocessing the data (which is essentially what processing Liquid in Markdown would be), but about post-processing the converted HTML. As I indicated, I’m *not* a target user for this at the moment as I don't use anything like Netlify images or some other image CDN.

Yes, one can have a `MyApp.MdexConverter` that just wraps `MdexConverter` and then does the netlify image transformation, but that feels less usable, less composable, and less easily shared than having some sort of callback mechanism.

I opened this feature request mainly because the closed pull request had a description that didn't *quite* match its active use case and I think that it's a use case worth considering.

**Comment by andyl** [comment]
> Netlify image transformation

I'm also interested in composable/sharable text conversion.  Just put up an experimental repo with this in mind: [conpipe](https://github.com/andyl/conpipe).  This is what I used to to the Liquid/Markdown processing.

I think the @paradox460 use case would be a fit for this, without needing a callback from Tableau.

**Comment by mhanberg** [comment]
I think I will modify the build pipeline so that we fully render the graph before calling the a `pre_write` extension type, and hydrate the content into the `site.pages` key in the token/assigns, you can modify it however you want, then we'll write it to disk.

I think that satisfies being able to modify HTML before it gets written but without having to care about every extension that is creating HTML or whatever content is being created
