### ISSUE TITLE
Specify Converter in Front Matter

### ISSUE THREAD

**Issue by andyl** [elixir-tools/tableau#112]
Thanks very much for 0.18, especially for the ability to specify a converter module in `config.exs`.  (eg `md: MyMdConverter, ...`).

I ran into a problem while migrating `elixir-lang.org` from Jekyll to Tableau:
- `elixir-lang.org` uses Liquid templates
- I have run into bugs with Elixir's Liquid processor (called Solid)
- The bugs occur with Liquid tags for conditionals and loops, maybe others
- When these bugs are encountered, it would be nice to just rewrite the broken page using EEx tags

With Tableau, AFAIK it's possible to set a default Layout module in `config.exs`, then override the layout with page front-matter.

Feature request: analogous to Layouts, allow the Converter to be set with front-matter

```markdown
---
title: "My Page" 
layout: MyApp.CustomLayout
permalink: /mypage
converter: MyApp.CustomConverter
---
# Hello World
....
```

**Comment by mhanberg** [comment]
Seems reasonable. 

If you can reproduce the bugs in solid could you report those to the project? Just to be a good citizen 🫡

**Comment by andyl** [comment]
> can you report?

FYI here's the first one.  https://github.com/edgurgel/solid/issues/144  More to come.
