### ISSUE TITLE
Consider a project name change?

### ISSUE THREAD

**Issue by sanford** [elixir-tools/tableau#18]
Awesome project.  I'd love to see it get more popular.

Perhaps the authors might consider a name change?  

Tableau is popular business software now owned by Salesforce that has been trademarked globally. 

US Trademark Registration Number | 6919884
International Registration Number | 1655549

Which means if this project becomes popular, Salesforce's lawyers are obligated to ask you to change the project name (or shut down) to protect their trademark.  

If they don't protect it, the run the chance of losing it.  

It's only a matter of time before that email arrives.  

Plus there's a good chance most people will be confused the first time they see "powered by Tableau" and assume it's the business software (like I did).

**Comment by mhanberg** [comment]
I'm not very concerned about this.
