### ISSUE TITLE
HEEX Example?

### ISSUE THREAD

**Issue by andyl** [elixir-tools/tableau#53]
Can anyone post a link to a tableau site that uses HEEX instead of temple?  TIA

**Comment by mhanberg** [comment]
https://github.com/mhanberg/tableau_demo_heex

The main thing is in your root layout, you need to pipe the template into `Phoenix.HTML.Safe.to_iodata/1`

```elixir
defmodule TableauDemoHeex.RootLayout do
  use Tableau.Layout
  use Phoenix.Component

  def template(assigns) do
    ~H"""
    <!DOCTYPE HTML>
    <html>
      <head>
        <title>Tableau EEx Demo</title>
      </head>
      <body>
        <%= render(@inner_content) %>
      </body>
    </html>
    """
    |> Phoenix.HTML.Safe.to_iodata()
  end
end
```

**Comment by andyl** [comment]
That's what I needed thank you!

**Comment by mhanberg** [comment]
If possible, please share what you build! 😄

**Comment by andyl** [comment]
Here's a repo that I'm using for prototypes and tests: [stat1](https://github.com/andyl/stat1)

When I have a working site I'll post it here...
