### ISSUE TITLE
Create a discussions page

### ISSUE THREAD

**Issue by sylvester-roos** [elixir-tools/tableau#70]
I (and maybe others) would like to occasionally ask a question about using Tableau, and issues aren't the right place for that.

Suggestion: create a discussions page like in the [Temple](https://github.com/mhanberg/temple) repository

**Comment by andyl** [comment]
Another option: enable Github's 'discussion' feature for this repo.

**Comment by mhanberg** [comment]
I think that's what they were saying. 

I have an umbrella one for all elixir tools projects but that's more for the related editor/LSP projects. 

I'll enable discussions for tableau once I'm back at a computer.
