### ISSUE TITLE
Overloaded term: PAGES

### ISSUE THREAD

**Issue by andyl** [elixir-tools/tableau#88]
Tableau uses the term 'page' for two different features.  

The first is the `Tableau.Page` macro, used to generate html from templates that are hand-coded in a module.

The second is the `Tableau.PageExtension` module, which read markdown files from the `_pages` directory (by default) and generates html.

IMO the use of the overloaded term 'page' for two different features makes it more difficult for beginners to understand and reason about building with Tableau.

Suggestion: 
- rename `Tableau.PageExtension` to `Tableau.DocExtension` 
- change the default directory from `_pages` to `_docs` 

Note: instead of 'docs', a good alternate term might be 'text' or 'content'...

LMK if you would accept a PR for this change.

**Comment by mhanberg** [comment]
Might actually be a sign to pivot into a "generator" extension that can automatically generate pages from plaintext files

The posts and pages extensions are almost the same, and there has been interest in using markup languages other than markdown.

I'll noodle on this idea into what it could look like.

**Comment by andyl** [comment]
Nice.  Would be interesting to have flexibility for `asciidoc`, `mediawiki`, etc. 

That would be easier for people to generate output formats like PDF/DocBook.

Maybe somehow integrate with ExDoc...
 
Brainstorming terms: `Tableau.MakeExtension` / `_make`

**Comment by mhanberg** [comment]
Merged a PR that reworks how the Page and Post extensions work, and I think it aligned for me that the page terminology should stay.

I plan on updating the docs/guides in a way that makes that easier to understand.
